# Generated by Django 5.0.14 on 2026-04-26 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("enrollment", "Enrollment"),
                            ("assignment", "Assignment"),
                            ("grade", "Grade"),
                            ("recording", "Recording"),
                            ("attendance", "Attendance"),
                            ("certificate", "Certificate"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField(max_length=1200)),
                ("action_url", models.CharField(blank=True, max_length=300)),
                ("event_key", models.CharField(max_length=160, unique=True)),
                ("is_read", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
