export const OPTION_SOURCES = {
  mentorUsers: {
    endpoint: 'admin/users/?role=mentor',
    getValue: (item) => item.id,
    getLabel: (item) => `${item.full_name || item.email} (${item.email})`,
  },
  studentUsers: {
    endpoint: 'admin/users/?role=student',
    getValue: (item) => item.id,
    getLabel: (item) => `${item.full_name || item.email} (${item.email})`,
  },
  adminUsers: {
    endpoint: 'admin/users/',
    getValue: (item) => item.id,
    getLabel: (item) => `${item.full_name || item.email} (${item.role})`,
  },
  categories: {
    endpoint: 'courses/categories/',
    getValue: (item) => item.id,
    getLabel: (item) => item.name,
  },
  courses: {
    endpoint: 'courses/courses/',
    getValue: (item) => item.slug,
    getLabel: (item) => item.title,
  },
  coursesById: {
    endpoint: 'courses/courses/',
    getValue: (item) => item.id,
    getLabel: (item) => item.title,
  },
  paymentMethods: {
    endpoint: 'enrollments/payment-methods/',
    getValue: (item) => item.id,
    getLabel: (item) => item.account_label ? `${item.name} (${item.account_label})` : item.name,
  },
  assignments: {
    endpoint: 'assignments/list/',
    getValue: (item) => item.id,
    getLabel: (item) => item.title,
  },
  attendanceSessions: {
    endpoint: 'attendance/sessions/',
    getValue: (item) => item.id,
    getLabel: (item) => item.title || item.course_title || `Session ${item.id}`,
  },
  certificateTemplates: {
    endpoint: 'certificates/templates/',
    getValue: (item) => item.id,
    getLabel: (item) => item.title,
  },
  blogCategories: {
    endpoint: 'blogs/categories/',
    getValue: (item) => item.id,
    getLabel: (item) => item.name,
  },
  blogPosts: {
    endpoint: 'blogs/posts/',
    getValue: (item) => item.id,
    getLabel: (item) => item.title,
  },
};

export const ADMIN_NAV_GROUPS = [
  {
    label: 'Overview',
    items: ['overview'],
  },
  {
    label: 'People',
    items: ['users', 'students', 'mentors'],
  },
  {
    label: 'Academics',
    items: [
      'categories',
      'courses',
      'paymentMethods',
      'enrollments',
      'assignments',
      'assignmentSubmissions',
      'attendanceSessions',
      'attendanceRecords',
      'certificateTemplates',
      'issuedCertificates',
      'recordings',
    ],
  },
  {
    label: 'Content',
    items: ['blogCategories', 'blogPosts', 'blogComments', 'freeResources', 'siteSettings'],
  },
  {
    label: 'Support',
    items: ['callbackRequests'],
  },
];

export const ADMIN_RESOURCES = {
  overview: {
    kind: 'dashboard',
    title: 'Admin Overview',
    description: 'Track platform activity, team counts, pending approvals, and the newest operations signals.',
  },
  users: {
    title: 'Accounts',
    endpoint: 'admin/users/',
    idKey: 'id',
    singularLabel: 'account',
    columns: [
      { key: 'full_name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'is_active', label: 'Active', type: 'boolean' },
    ],
    fields: [
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'first_name', label: 'First name', type: 'text' },
      { name: 'last_name', label: 'Last name', type: 'text' },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: [
          { value: 'admin', label: 'Admin' },
          { value: 'mentor', label: 'Mentor' },
          { value: 'student', label: 'Student' },
        ],
      },
      { name: 'phone_number', label: 'Phone number', type: 'text' },
      { name: 'password', label: 'Password', type: 'password', helper: 'Required for new accounts. Leave blank to keep the current password.' },
      { name: 'is_phone_verified', label: 'Phone verified', type: 'checkbox' },
      { name: 'is_active', label: 'Account active', type: 'checkbox' },
      { name: 'is_staff', label: 'Staff access', type: 'checkbox' },
    ],
  },
  students: {
    title: 'Student Profiles',
    endpoint: 'students/',
    idKey: 'id',
    singularLabel: 'student profile',
    columns: [
      { key: 'student_id', label: 'Student ID' },
      { key: 'full_name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'phone_number', label: 'Phone' },
    ],
    fields: [
      { name: 'user', label: 'Student account', type: 'select', optionSource: 'studentUsers', required: true },
      { name: 'date_of_birth', label: 'Date of birth', type: 'date' },
      { name: 'phone_number', label: 'Phone number', type: 'text' },
    ],
  },
  mentors: {
    title: 'Mentor Profiles',
    endpoint: 'mentors/',
    idKey: 'id',
    singularLabel: 'mentor profile',
    fileFields: ['photo'],
    columns: [
      { key: 'mentor_id', label: 'Mentor ID' },
      { key: 'full_name', label: 'Name' },
      { key: 'expertise', label: 'Expertise' },
      { key: 'experience', label: 'Years' },
    ],
    fields: [
      { name: 'user', label: 'Mentor account', type: 'select', optionSource: 'mentorUsers', required: true },
      { name: 'photo', label: 'Photo', type: 'file' },
      { name: 'expertise', label: 'Expertise', type: 'text' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'website', label: 'Website', type: 'url' },
      { name: 'experience', label: 'Experience (years)', type: 'number', min: 0 },
      { name: 'current_company', label: 'Current company', type: 'text' },
    ],
  },
  categories: {
    title: 'Course Categories',
    endpoint: 'courses/categories/',
    idKey: 'id',
    singularLabel: 'category',
    fileFields: ['image'],
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
      { key: 'show_on_home', label: 'Home', type: 'boolean' },
      { key: 'sort_order', label: 'Order' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'short_description', label: 'Card description', type: 'textarea' },
      { name: 'image', label: 'Card image', type: 'file' },
      { name: 'badge', label: 'Badge', type: 'text' },
      { name: 'icon_name', label: 'Icon name', type: 'text' },
      { name: 'show_on_home', label: 'Show on homepage', type: 'checkbox' },
      { name: 'sort_order', label: 'Display order', type: 'number', min: 0 },
    ],
  },
  courses: {
    title: 'Courses',
    endpoint: 'courses/courses/',
    idKey: 'slug',
    singularLabel: 'course',
    fileFields: ['thumbnail'],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category_name', label: 'Category' },
      { key: 'mentor_name', label: 'Mentor' },
      { key: 'is_published', label: 'Published', type: 'boolean' },
      { key: 'is_featured', label: 'Featured', type: 'boolean' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'mentor', label: 'Primary mentor', type: 'select', optionSource: 'mentorUsers', required: true },
      { name: 'category', label: 'Category', type: 'select', optionSource: 'categories' },
      { name: 'short_description', label: 'Short description', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'thumbnail', label: 'Thumbnail', type: 'file' },
      { name: 'display_video', label: 'Display video URL', type: 'url' },
      { name: 'duration_weeks', label: 'Duration (weeks)', type: 'number', min: 1, required: true },
      { name: 'syllabus_url', label: 'Syllabus URL', type: 'url' },
      { name: 'detail_badge_text', label: 'Detail badge text', type: 'text' },
      { name: 'actual_price', label: 'Actual price', type: 'number', min: 0, step: '0.01', required: true },
      { name: 'discounted_price', label: 'Discounted price', type: 'number', min: 0, step: '0.01' },
      { name: 'is_discount_active', label: 'Discount active', type: 'checkbox' },
      { name: 'start_date', label: 'Start date', type: 'date', required: true },
      { name: 'live_days', label: 'Live days', type: 'text', required: true },
      { name: 'live_time', label: 'Live time', type: 'text', required: true },
      { name: 'total_hours', label: 'Total hours', type: 'number', min: 0 },
      {
        name: 'language',
        label: 'Language',
        type: 'select',
        required: true,
        options: [
          { value: 'en', label: 'English' },
          { value: 'np', label: 'Nepali' },
          { value: 'en_np', label: 'English & Nepali' },
        ],
      },
      {
        name: 'level',
        label: 'Level',
        type: 'select',
        required: true,
        options: [
          { value: 'beginner', label: 'Beginner' },
          { value: 'intermediate', label: 'Intermediate' },
          { value: 'advanced', label: 'Advanced' },
        ],
      },
      { name: 'total_seats', label: 'Total seats', type: 'number', min: 0 },
      { name: 'enrolled_students', label: 'Enrolled students', type: 'number', min: 0 },
      { name: 'rating_avg', label: 'Average rating', type: 'number', min: 0, step: '0.01' },
      { name: 'rating_count', label: 'Rating count', type: 'number', min: 0 },
      { name: 'certificate_available', label: 'Certificate available', type: 'checkbox' },
      { name: 'is_live', label: 'Live course', type: 'checkbox' },
      { name: 'is_featured', label: 'Featured course', type: 'checkbox' },
      { name: 'featured_order', label: 'Featured order', type: 'number', min: 0 },
      {
        name: 'featured_theme',
        label: 'Featured theme',
        type: 'select',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
        ],
      },
      {
        name: 'featured_layout',
        label: 'Featured layout',
        type: 'select',
        options: [
          { value: 'media-left', label: 'Media left' },
          { value: 'media-right', label: 'Media right' },
        ],
      },
      { name: 'featured_eyebrow', label: 'Featured eyebrow', type: 'text' },
      { name: 'support_value', label: 'Support value', type: 'text' },
      { name: 'support_label', label: 'Support label', type: 'text' },
      { name: 'is_published', label: 'Published', type: 'checkbox' },
      {
        name: 'learning_points',
        label: 'What students will learn',
        type: 'repeater',
        itemLabel: 'Point',
        itemFields: [{ name: 'text', label: 'Text', type: 'text', required: true }],
      },
      {
        name: 'requirements',
        label: 'Requirements',
        type: 'repeater',
        itemLabel: 'Requirement',
        itemFields: [{ name: 'text', label: 'Text', type: 'text', required: true }],
      },
      {
        name: 'target_audience',
        label: 'Target audience',
        type: 'repeater',
        itemLabel: 'Audience item',
        itemFields: [{ name: 'text', label: 'Text', type: 'text', required: true }],
      },
      {
        name: 'tags',
        label: 'Tags',
        type: 'repeater',
        itemLabel: 'Tag',
        itemFields: [
          { name: 'text', label: 'Tag text', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'faqs',
        label: 'FAQs',
        type: 'repeater',
        itemLabel: 'FAQ',
        itemFields: [
          { name: 'question', label: 'Question', type: 'text', required: true },
          { name: 'answer', label: 'Answer', type: 'textarea', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'modules',
        label: 'Curriculum modules',
        type: 'repeater',
        itemLabel: 'Module',
        itemFields: [
          { name: 'title', label: 'Title', type: 'text', required: true },
          { name: 'description', label: 'Description', type: 'textarea' },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
          {
            name: 'points',
            label: 'Module points',
            type: 'repeater',
            itemLabel: 'Point',
            itemFields: [
              { name: 'text', label: 'Point text', type: 'text', required: true },
              { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
            ],
          },
        ],
      },
      {
        name: 'comparison_points',
        label: 'Comparison points',
        type: 'repeater',
        itemLabel: 'Comparison point',
        itemFields: [
          {
            name: 'side',
            label: 'Side',
            type: 'select',
            required: true,
            options: [
              { value: 'school', label: 'School' },
              { value: 'others', label: 'Others' },
            ],
          },
          { name: 'text', label: 'Text', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'technology_categories',
        label: 'Technology sections',
        type: 'repeater',
        itemLabel: 'Technology section',
        itemFields: [
          { name: 'name', label: 'Section name', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
          {
            name: 'items',
            label: 'Technology items',
            type: 'repeater',
            itemLabel: 'Technology item',
            itemFields: [
              { name: 'name', label: 'Name', type: 'text', required: true },
              { name: 'icon_url', label: 'Icon URL', type: 'url' },
              { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
            ],
          },
        ],
      },
      {
        name: 'builder_items',
        label: 'Builder items',
        type: 'repeater',
        itemLabel: 'Builder item',
        itemFields: [
          { name: 'title', label: 'Title', type: 'text', required: true },
          { name: 'icon_name', label: 'Icon name', type: 'text' },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'certificate_points',
        label: 'Certificate points',
        type: 'repeater',
        itemLabel: 'Certificate point',
        itemFields: [
          { name: 'text', label: 'Text', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'mentor_spotlights',
        label: 'Mentor spotlight cards',
        type: 'repeater',
        itemLabel: 'Mentor spotlight',
        itemFields: [
          { name: 'name', label: 'Name', type: 'text', required: true },
          { name: 'role', label: 'Role', type: 'text' },
          { name: 'photo_url', label: 'Photo URL', type: 'url' },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
    ],
  },
  enrollments: {
    title: 'Enrollments',
    endpoint: 'enrollments/',
    idKey: 'id',
    singularLabel: 'enrollment',
    fileFields: ['payment_screenshot'],
    columns: [
      { key: 'first_name', label: 'First name' },
      { key: 'last_name', label: 'Last name' },
      { key: 'email', label: 'Email' },
      { key: 'course_title', label: 'Course' },
      { key: 'payment_method_name', label: 'Payment' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'first_name', label: 'First name', type: 'text', required: true },
      { name: 'last_name', label: 'Last name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'whatsapp_number', label: 'WhatsApp number', type: 'text', required: true },
      { name: 'course', label: 'Course', type: 'select', optionSource: 'coursesById', required: true },
      { name: 'payment_method', label: 'Payment method', type: 'select', optionSource: 'paymentMethods', required: true },
      { name: 'payment_screenshot', label: 'Payment screenshot', type: 'file' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'verified', label: 'Verified' },
        ],
      },
    ],
  },
  paymentMethods: {
    title: 'Payment Methods',
    endpoint: 'enrollments/payment-methods/',
    idKey: 'id',
    singularLabel: 'payment method',
    fileFields: ['qr_code'],
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'account_label', label: 'Account' },
      { key: 'is_active', label: 'Active', type: 'boolean' },
      { key: 'sort_order', label: 'Sort' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'account_label', label: 'Account label', type: 'text' },
      { name: 'qr_code', label: 'QR code', type: 'file', required: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
      { name: 'sort_order', label: 'Sort order', type: 'number', min: 0 },
    ],
  },
  assignments: {
    title: 'Assignments',
    endpoint: 'assignments/list/',
    idKey: 'id',
    singularLabel: 'assignment',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'course_title', label: 'Course' },
      { key: 'due_date', label: 'Due date', type: 'datetime' },
    ],
    fields: [
      { name: 'course', label: 'Course', type: 'select', optionSource: 'coursesById', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'due_date', label: 'Due date', type: 'datetime-local', required: true },
    ],
  },
  assignmentSubmissions: {
    title: 'Assignment Submissions',
    endpoint: 'assignments/submissions/',
    idKey: 'id',
    singularLabel: 'submission',
    columns: [
      { key: 'assignment_title', label: 'Assignment' },
      { key: 'student_name', label: 'Student' },
      { key: 'status', label: 'Status' },
      { key: 'marks_obtained', label: 'Marks' },
    ],
    fields: [
      { name: 'assignment', label: 'Assignment', type: 'select', optionSource: 'assignments', required: true },
      { name: 'student', label: 'Student', type: 'select', optionSource: 'studentUsers', required: true },
      { name: 'submission_link', label: 'Submission URL', type: 'url' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'submitted', label: 'Submitted' },
          { value: 'graded', label: 'Graded' },
        ],
      },
      { name: 'marks_obtained', label: 'Marks obtained', type: 'number', min: 0 },
    ],
  },
  attendanceSessions: {
    title: 'Attendance Sessions',
    endpoint: 'attendance/sessions/',
    idKey: 'id',
    singularLabel: 'attendance session',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'course_title', label: 'Course' },
      { key: 'date', label: 'Date', type: 'date' },
    ],
    fields: [
      { name: 'course', label: 'Course', type: 'select', optionSource: 'coursesById', required: true },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'start_time', label: 'Start time', type: 'time' },
      { name: 'end_time', label: 'End time', type: 'time' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  attendanceRecords: {
    title: 'Attendance Records',
    endpoint: 'attendance/records/',
    idKey: 'id',
    singularLabel: 'attendance record',
    columns: [
      { key: 'session_title', label: 'Session' },
      { key: 'student_name', label: 'Student' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'session', label: 'Session', type: 'select', optionSource: 'attendanceSessions', required: true },
      { name: 'student', label: 'Student', type: 'select', optionSource: 'studentUsers', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { value: 'present', label: 'Present' },
          { value: 'absent', label: 'Absent' },
          { value: 'late', label: 'Late' },
          { value: 'excused', label: 'Excused' },
        ],
      },
    ],
  },
  certificateTemplates: {
    title: 'Certificate Templates',
    endpoint: 'certificates/templates/',
    idKey: 'id',
    singularLabel: 'certificate template',
    fileFields: ['template_file'],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'course_title', label: 'Course' },
      { key: 'is_published', label: 'Published', type: 'boolean' },
    ],
    fields: [
      { name: 'course', label: 'Course', type: 'select', optionSource: 'coursesById', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'template_file', label: 'Template file', type: 'file' },
      { name: 'is_published', label: 'Published', type: 'checkbox' },
    ],
  },
  issuedCertificates: {
    title: 'Issued Certificates',
    endpoint: 'certificates/issued/',
    idKey: 'id',
    singularLabel: 'issued certificate',
    columns: [
      { key: 'certificate_title', label: 'Certificate' },
      { key: 'student_name', label: 'Student' },
      { key: 'status', label: 'Status' },
      { key: 'unique_id', label: 'Unique ID' },
    ],
    fields: [
      { name: 'certificate', label: 'Certificate template', type: 'select', optionSource: 'certificateTemplates', required: true },
      { name: 'student', label: 'Student', type: 'select', optionSource: 'studentUsers', required: true },
      { name: 'download_link', label: 'Download link', type: 'url' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'pending', label: 'Pending' },
          { value: 'issued', label: 'Issued' },
        ],
      },
    ],
  },
  recordings: {
    title: 'Class Recordings',
    endpoint: 'recordings/',
    idKey: 'id',
    singularLabel: 'recording',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'course_title', label: 'Course' },
      { key: 'video_provider', label: 'Provider' },
      { key: 'is_unlisted', label: 'Unlisted', type: 'boolean' },
      { key: 'uploaded_by_name', label: 'Uploaded by' },
    ],
    fields: [
      { name: 'course', label: 'Course', type: 'select', optionSource: 'coursesById', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'video_url', label: 'Video URL', type: 'url', required: true },
      { name: 'duration_seconds', label: 'Duration seconds', type: 'number' },
      { name: 'is_unlisted', label: 'YouTube unlisted/private catalog', type: 'checkbox' },
    ],
  },
  blogCategories: {
    title: 'Blog Categories',
    endpoint: 'blogs/categories/',
    idKey: 'id',
    singularLabel: 'blog category',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'meta_title', label: 'Meta title', type: 'text' },
      { name: 'meta_description', label: 'Meta description', type: 'textarea' },
    ],
  },
  blogPosts: {
    title: 'Blog Posts',
    endpoint: 'blogs/posts/',
    idKey: 'slug',
    singularLabel: 'blog post',
    fileFields: ['featured_image'],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category_name', label: 'Category' },
      { key: 'author_name', label: 'Author' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'author', label: 'Author', type: 'select', optionSource: 'adminUsers', required: true },
      { name: 'category', label: 'Category', type: 'select', optionSource: 'blogCategories' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'featured_image', label: 'Featured image', type: 'file' },
      { name: 'meta_title', label: 'Meta title', type: 'text' },
      { name: 'meta_description', label: 'Meta description', type: 'textarea' },
      { name: 'keywords', label: 'Keywords', type: 'text' },
      { name: 'read_time', label: 'Read time (minutes)', type: 'number', min: 1 },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'draft', label: 'Draft' },
          { value: 'published', label: 'Published' },
        ],
      },
      { name: 'is_published', label: 'Publicly published', type: 'checkbox' },
      { name: 'published_at', label: 'Published at', type: 'datetime-local' },
    ],
  },
  blogComments: {
    title: 'Blog Comments',
    endpoint: 'blogs/comments/',
    idKey: 'id',
    singularLabel: 'comment',
    columns: [
      { key: 'post_title', label: 'Post' },
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'approved', label: 'Approved', type: 'boolean' },
    ],
    fields: [
      { name: 'post', label: 'Blog post', type: 'select', optionSource: 'blogPosts', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'content', label: 'Comment', type: 'textarea', required: true },
      { name: 'approved', label: 'Approved', type: 'checkbox' },
    ],
  },
  freeResources: {
    title: 'Free Resources',
    endpoint: 'site/resources/',
    idKey: 'slug',
    singularLabel: 'free resource',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'resource_type', label: 'Type' },
      { key: 'level', label: 'Level' },
      { key: 'is_published', label: 'Published', type: 'boolean' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'short_description', label: 'Short description', type: 'textarea', required: true },
      { name: 'resource_type', label: 'Resource type', type: 'text', required: true },
      { name: 'count_label', label: 'Count label', type: 'text', required: true },
      {
        name: 'icon_key',
        label: 'Icon',
        type: 'select',
        options: [
          'workflow',
          'code2',
          'notebook',
          'layout',
          'server',
          'database',
          'filetext',
          'pen',
          'book',
          'video',
          'lightbulb',
          'revision',
        ].map((value) => ({ value, label: value })),
      },
      { name: 'level', label: 'Level', type: 'text' },
      { name: 'format', label: 'Format', type: 'text' },
      { name: 'estimate_time', label: 'Estimate time', type: 'text' },
      { name: 'updated_label', label: 'Updated label', type: 'text' },
      { name: 'accent_label', label: 'Accent label', type: 'text' },
      { name: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { name: 'preview_title', label: 'Preview title', type: 'text' },
      { name: 'preview_code', label: 'Preview code', type: 'textarea' },
      { name: 'is_published', label: 'Published', type: 'checkbox' },
      { name: 'sort_order', label: 'Sort order', type: 'number', min: 0 },
      {
        name: 'outcomes',
        label: 'Outcomes',
        type: 'repeater',
        itemLabel: 'Outcome',
        itemFields: [
          { name: 'text', label: 'Text', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'modules',
        label: 'Modules',
        type: 'repeater',
        itemLabel: 'Module',
        itemFields: [
          { name: 'title', label: 'Title', type: 'text', required: true },
          { name: 'detail', label: 'Detail', type: 'textarea', required: true },
          { name: 'duration', label: 'Duration', type: 'text' },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'workflow_steps',
        label: 'Workflow steps',
        type: 'repeater',
        itemLabel: 'Workflow step',
        itemFields: [
          { name: 'title', label: 'Title', type: 'text', required: true },
          { name: 'detail', label: 'Detail', type: 'textarea', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
      {
        name: 'includes',
        label: 'Included items',
        type: 'repeater',
        itemLabel: 'Included item',
        itemFields: [
          { name: 'text', label: 'Text', type: 'text', required: true },
          { name: 'sort_order', label: 'Sort', type: 'number', min: 0 },
        ],
      },
    ],
  },
  siteSettings: {
    kind: 'singleton',
    title: 'Site Settings',
    endpoint: 'site/settings/',
    idKey: 'id',
    singularLabel: 'site setting',
    fields: [
      { name: 'site_name', label: 'Site name', type: 'text', required: true },
      { name: 'support_email', label: 'Support email', type: 'email' },
      { name: 'support_phone', label: 'Support phone', type: 'text' },
      { name: 'support_whatsapp', label: 'Support WhatsApp', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'office_hours', label: 'Office hours', type: 'text' },
      { name: 'footer_tagline', label: 'Footer tagline', type: 'textarea' },
    ],
  },
  callbackRequests: {
    title: 'Callback Requests',
    endpoint: 'site/callback-requests/',
    idKey: 'id',
    singularLabel: 'callback request',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'phone_number', label: 'Phone' },
      { key: 'enquiry_for', label: 'Enquiry' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'country_code', label: 'Country code', type: 'text' },
      { name: 'phone_number', label: 'Phone number', type: 'text', required: true },
      {
        name: 'enquiry_for',
        label: 'Enquiry for',
        type: 'select',
        options: [
          { value: 'online_course', label: 'Online Course' },
          { value: 'live_cohort', label: 'Live Cohort' },
          { value: 'offline_classes', label: 'Offline Classes' },
          { value: 'career_guidance', label: 'Career Guidance' },
          { value: 'other', label: 'Other' },
        ],
      },
      { name: 'message', label: 'Message', type: 'textarea' },
      { name: 'source_page', label: 'Source page', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { value: 'new', label: 'New' },
          { value: 'in_progress', label: 'In progress' },
          { value: 'resolved', label: 'Resolved' },
          { value: 'spam', label: 'Spam' },
        ],
      },
      { name: 'admin_note', label: 'Admin note', type: 'textarea' },
    ],
  },
};
